name: Build Amiigo
services: docker
sudo: required

on: [push]
jobs:
  Build:
  runs-on: ubuntu-latest
  steps:
    uses: actions/checkout@v1
    name: Update repo.
    run: git submodule update --init --recursive

    name: Install devkitpro
    run: docker pull devkitpro/devkita64

    name: Make Amiigo
    run: docker run -e ENABLE_COMPATIBILITY_REPORTING -v $TRAVIS_BUILD_DIR:/Amiigo devkitpro/devkita64 /bin/bash -ex make
    uses: actions/upload-artifact@master
    with:
      name: Amiigo
      path: Amiigo.nro